### ISSUE TITLE
ggarrange and yaxis title spacing

### ISSUE THREAD

**Issue by orb16** [baptiste/egg#4]
ggarrange is such a great function! I have a question: at the moment the y axes and y titles seem to be one element, such that if you have different widths of the y axis breaks, the y axis titles don't align:

```{r}
require(ggplot2)
require(egg)

facet_1 <- ggplot(iris, aes(x = Petal.Length, y = Sepal.Length)) + 
  geom_point(aes(colour = Species)) + 
  theme_bw() + 
  facet_wrap(~Species)

facet_2 <- ggplot(iris, aes(x = Petal.Length, y = Sepal.Length / 1000)) + 
  geom_point(aes(colour = Species)) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  facet_wrap(~Species)

ggarrange(plots = list(facet_1 + theme(legend.position = "none"), 
                       facet_2), 
          heights = c(1, 1)
          )
```

For my purposes I've made a (super) hacky fix - but is there a better way? This might be directed better at a mailing list perhaps, but I thought I would ask. Could also use `facet_grid`, but ideally they are separate plots (in case you are using separate geoms, etc).

```{r}
notworkings <- arrangeGrob(
  ggarrange(plots=list(facet_1 + 
                         theme(axis.title.y = element_blank(),
                               legend.position = "none") + 
                         ggtitle("(a)"),  
                       facet_2 + 
                         theme(axis.title.y = element_blank()) + 
                         ggtitle("(b)")), debug=FALSE, draw = FALSE),
  left = textGrob(label = "Seedling survival \U00b1 SE                                Relative growth rate \U00b1 95% CI",
                  rot = 90, hjust = 0.4))

grid.newpage()

grid.draw(notworkings)
```

**Comment by baptiste** [comment]
From what I understand you should be using `gtable` directly, because `ggarrange` has some built-in choices on how to align individual plot elements relative to each other that do not correspond to what you want.

```
grid.draw(rbind(ggplotGrob(facet_1 + theme(legend.position = "none")), ggplotGrob(facet_2)))
```

<img width="733" alt="screen shot 2017-06-21 at 9 52 33 am" src="https://user-images.githubusercontent.com/18970/27375520-5fdbd084-5667-11e7-9f24-22dd0f3ecfdb.png">

I should point out that this `egg` package has always been just a proof of principle; I don't intend to improve it much or release it (in my experience ggplot2 is such a moving target that it's become a time sink to fix packages after every update). Users should however feel free to clone and adapt it to their needs.

**Comment by orb16** [comment]
Ah I see - thanks for the pointer!
